<?php

namespace App\DataProviders;

abstract class CountryDataProvider
{
    public static function data(): array
    {
        return [
            ['id' => '1', 'name' => 'afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'calling_code' => '+93'],
            ['id' => '2', 'name' => 'albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'calling_code' => '+355'],
            ['id' => '3', 'name' => 'algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'calling_code' => '+213'],
            ['id' => '4', 'name' => 'american samoa', 'iso2' => 'AS', 'iso3' => 'ASM', 'calling_code' => '+1-684'],
            ['id' => '5', 'name' => 'andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'calling_code' => '+376'],
            ['id' => '6', 'name' => 'angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'calling_code' => '+244'],
            ['id' => '7', 'name' => 'anguilla', 'iso2' => 'AI', 'iso3' => 'AIA', 'calling_code' => '+1-264'],
            ['id' => '8', 'name' => 'antarctica', 'iso2' => 'AQ', 'iso3' => 'ATA', 'calling_code' => ''],
            ['id' => '9', 'name' => 'antigua and barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'calling_code' => '+1-268'],
            ['id' => '10', 'name' => 'argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'calling_code' => '+54'],
            ['id' => '11', 'name' => 'armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'calling_code' => '+374'],
            ['id' => '12', 'name' => 'aruba', 'iso2' => 'AW', 'iso3' => 'ABW', 'calling_code' => '+297'],
            ['id' => '13', 'name' => 'australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'calling_code' => '+61'],
            ['id' => '14', 'name' => 'austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'calling_code' => '+43'],
            ['id' => '15', 'name' => 'azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'calling_code' => '+994'],
            ['id' => '16', 'name' => 'bahamas the', 'iso2' => 'BS', 'iso3' => 'BHS', 'calling_code' => '+1-242'],
            ['id' => '17', 'name' => 'bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'calling_code' => '+973'],
            ['id' => '18', 'name' => 'bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'calling_code' => '+880'],
            ['id' => '19', 'name' => 'barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'calling_code' => '+1-246'],
            ['id' => '20', 'name' => 'belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'calling_code' => '+375'],
            ['id' => '21', 'name' => 'belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'calling_code' => '+32'],
            ['id' => '22', 'name' => 'belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'calling_code' => '+501'],
            ['id' => '23', 'name' => 'benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'calling_code' => '+229'],
            ['id' => '24', 'name' => 'bermuda', 'iso2' => 'BM', 'iso3' => 'BMU', 'calling_code' => '+1-441'],
            ['id' => '25', 'name' => 'bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'calling_code' => '+975'],
            ['id' => '26', 'name' => 'bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'calling_code' => '+591'],
            ['id' => '27', 'name' => 'bosnia and herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'calling_code' => '+387'],
            ['id' => '28', 'name' => 'botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'calling_code' => '+267'],
            ['id' => '29', 'name' => 'bouvet island', 'iso2' => 'BV', 'iso3' => 'BVT', 'calling_code' => ''],
            ['id' => '30', 'name' => 'brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'calling_code' => '+55'],
            ['id' => '31', 'name' => 'british indian ocean territory', 'iso2' => 'IO', 'iso3' => 'IOT', 'calling_code' => ''],
            ['id' => '32', 'name' => 'brunei', 'iso2' => 'BN', 'iso3' => 'BRN', 'calling_code' => '+673'],
            ['id' => '33', 'name' => 'bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'calling_code' => '+359'],
            ['id' => '34', 'name' => 'burkina faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'calling_code' => '+226'],
            ['id' => '35', 'name' => 'burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'calling_code' => '+257'],
            ['id' => '36', 'name' => 'cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'calling_code' => '+855'],
            ['id' => '37', 'name' => 'cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'calling_code' => '+237'],
            ['id' => '38', 'name' => 'canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'calling_code' => '+1'],
            ['id' => '39', 'name' => 'cape verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'calling_code' => '+238'],
            ['id' => '40', 'name' => 'cayman islands', 'iso2' => 'KY', 'iso3' => 'CYM', 'calling_code' => '+1-345'],
            ['id' => '41', 'name' => 'central african republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'calling_code' => '+236'],
            ['id' => '42', 'name' => 'chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'calling_code' => '+235'],
            ['id' => '43', 'name' => 'chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'calling_code' => '+56'],
            ['id' => '44', 'name' => 'china', 'iso2' => 'CN', 'iso3' => 'CHN', 'calling_code' => '+86'],
            ['id' => '45', 'name' => 'christmas island', 'iso2' => 'CX', 'iso3' => 'CXR', 'calling_code' => '+61'],
            ['id' => '46', 'name' => 'cocos (keeling) islands', 'iso2' => 'CC', 'iso3' => 'CCK', 'calling_code' => '+61'],
            ['id' => '47', 'name' => 'colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'calling_code' => '+57'],
            ['id' => '48', 'name' => 'comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'calling_code' => '+269'],
            ['id' => '49', 'name' => 'congo', 'iso2' => 'CG', 'iso3' => 'COG', 'calling_code' => '+242'],
            ['id' => '50', 'name' => 'congo the democratic republic of the', 'iso2' => 'CD', 'iso3' => 'COD', 'calling_code' => '+243'],
            ['id' => '51', 'name' => 'cook islands', 'iso2' => 'CK', 'iso3' => 'COK', 'calling_code' => '+682'],
            ['id' => '52', 'name' => 'costa rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'calling_code' => '+506'],
            ['id' => '53', 'name' => 'cote d\'ivoire (ivory coast)', 'iso2' => 'CI', 'iso3' => 'CIV', 'calling_code' => '+225'],
            ['id' => '54', 'name' => 'croatia (hrvatska)', 'iso2' => 'HR', 'iso3' => 'HRV', 'calling_code' => '+385'],
            ['id' => '55', 'name' => 'cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'calling_code' => '+53'],
            ['id' => '56', 'name' => 'cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'calling_code' => '+357'],
            ['id' => '57', 'name' => 'czech republic', 'iso2' => 'CZ', 'iso3' => 'CZE', 'calling_code' => '+420'],
            ['id' => '58', 'name' => 'denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'calling_code' => '+45'],
            ['id' => '59', 'name' => 'djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'calling_code' => '+253'],
            ['id' => '60', 'name' => 'dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'calling_code' => '+1-767'],
            ['id' => '61', 'name' => 'dominican republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'calling_code' => '+1-809, +1-829, +1-849'],
            ['id' => '62', 'name' => 'east timor', 'iso2' => 'TL', 'iso3' => 'TLS', 'calling_code' => '+670'],
            ['id' => '63', 'name' => 'ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'calling_code' => '+593'],
            ['id' => '64', 'name' => 'egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'calling_code' => '+20'],
            ['id' => '65', 'name' => 'el salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'calling_code' => '+503'],
            ['id' => '66', 'name' => 'equatorial guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'calling_code' => '+240'],
            ['id' => '67', 'name' => 'eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'calling_code' => '+291'],
            ['id' => '68', 'name' => 'estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'calling_code' => '+372'],
            ['id' => '69', 'name' => 'ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'calling_code' => '+251'],
            ['id' => '70', 'name' => 'external territories of australia', 'iso2' => '', 'iso3' => '', 'calling_code' => ''],
            ['id' => '71', 'name' => 'falkland islands', 'iso2' => 'FK', 'iso3' => 'FLK', 'calling_code' => '+500'],
            ['id' => '72', 'name' => 'faroe islands', 'iso2' => 'FO', 'iso3' => 'FRO', 'calling_code' => '+298'],
            ['id' => '73', 'name' => 'fiji islands', 'iso2' => 'FJ', 'iso3' => 'FJI', 'calling_code' => '+679'],
            ['id' => '74', 'name' => 'finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'calling_code' => '+358'],
            ['id' => '75', 'name' => 'france', 'iso2' => 'FR', 'iso3' => 'FRA', 'calling_code' => '+33'],
            ['id' => '76', 'name' => 'french guiana', 'iso2' => 'GF', 'iso3' => 'GUF', 'calling_code' => '+594'],
            ['id' => '77', 'name' => 'french polynesia', 'iso2' => 'PF', 'iso3' => 'PYF', 'calling_code' => '+689'],
            ['id' => '78', 'name' => 'french southern territories', 'iso2' => 'TF', 'iso3' => 'ATF', 'calling_code' => ''],
            ['id' => '79', 'name' => 'gabon', 'iso2' => 'GA', 'iso3' => 'GAB', 'calling_code' => '+241'],
            ['id' => '80', 'name' => 'gambia the', 'iso2' => 'GM', 'iso3' => 'GMB', 'calling_code' => '+220'],
            ['id' => '81', 'name' => 'georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'calling_code' => '+995'],
            ['id' => '82', 'name' => 'germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'calling_code' => '+49'],
            ['id' => '83', 'name' => 'ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'calling_code' => '+233'],
            ['id' => '84', 'name' => 'gibraltar', 'iso2' => 'GI', 'iso3' => 'GIB', 'calling_code' => '+350'],
            ['id' => '85', 'name' => 'greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'calling_code' => '+30'],
            ['id' => '86', 'name' => 'greenland', 'iso2' => 'GL', 'iso3' => 'GRL', 'calling_code' => '+299'],
            ['id' => '87', 'name' => 'grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'calling_code' => '+1473'],
            ['id' => '88', 'name' => 'guadeloupe', 'iso2' => 'GP', 'iso3' => 'GLP', 'calling_code' => '+590'],
            ['id' => '89', 'name' => 'guam', 'iso2' => 'GU', 'iso3' => 'GUM', 'calling_code' => '+1671'],
            ['id' => '90', 'name' => 'guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'calling_code' => '+502'],
            ['id' => '91', 'name' => 'guernsey and alderney', 'iso2' => 'GG', 'iso3' => 'GGY', 'calling_code' => '+44'],
            ['id' => '92', 'name' => 'guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'calling_code' => '+224'],
            ['id' => '93', 'name' => 'guinea-bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'calling_code' => '+245'],
            ['id' => '94', 'name' => 'guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'calling_code' => '+592'],
            ['id' => '95', 'name' => 'haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'calling_code' => '+509'],
            ['id' => '96', 'name' => 'heard and mcdonald islands', 'iso2' => 'HM', 'iso3' => 'HMD', 'calling_code' => ''],
            ['id' => '97', 'name' => 'honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'calling_code' => '+504'],
            ['id' => '98', 'name' => 'hong kong s.a.r.', 'iso2' => 'HK', 'iso3' => 'HKG', 'calling_code' => '+852'],
            ['id' => '99', 'name' => 'hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'calling_code' => '+36'],
            ['id' => '100', 'name' => 'iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'calling_code' => '+354'],
            ['id' => '101', 'name' => 'india', 'iso2' => 'IN', 'iso3' => 'IND', 'calling_code' => '+91'],
            ['id' => '102', 'name' => 'indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'calling_code' => '+62'],
            ['id' => '103', 'name' => 'iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'calling_code' => '+98'],
            ['id' => '104', 'name' => 'iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'calling_code' => '+964'],
            ['id' => '105', 'name' => 'ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'calling_code' => '+353'],
            ['id' => '106', 'name' => 'israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'calling_code' => '+972'],
            ['id' => '107', 'name' => 'italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'calling_code' => '+39'],
            ['id' => '108', 'name' => 'jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'calling_code' => '+1876'],
            ['id' => '109', 'name' => 'japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'calling_code' => '+81'],
            ['id' => '110', 'name' => 'jersey', 'iso2' => 'JE', 'iso3' => 'JEY', 'calling_code' => '+44'],
            ['id' => '111', 'name' => 'jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'calling_code' => '+962'],
            ['id' => '112', 'name' => 'kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'calling_code' => '+7'],
            ['id' => '113', 'name' => 'kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'calling_code' => '+254'],
            ['id' => '114', 'name' => 'kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'calling_code' => '+686'],
            ['id' => '115', 'name' => 'korea north', 'iso2' => 'KP', 'iso3' => 'PRK', 'calling_code' => '+850'],
            ['id' => '116', 'name' => 'korea south', 'iso2' => 'KR', 'iso3' => 'KOR', 'calling_code' => '+82'],
            ['id' => '117', 'name' => 'kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'calling_code' => '+965'],
            ['id' => '118', 'name' => 'kyrgyzstan', 'iso2' => 'KG', 'iso3' => 'KGZ', 'calling_code' => '+996'],
            ['id' => '119', 'name' => 'laos', 'iso2' => 'LA', 'iso3' => 'LAO', 'calling_code' => '+856'],
            ['id' => '120', 'name' => 'latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'calling_code' => '+371'],
            ['id' => '121', 'name' => 'lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'calling_code' => '+961'],
            ['id' => '122', 'name' => 'lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'calling_code' => '+266'],
            ['id' => '123', 'name' => 'liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'calling_code' => '+231'],
            ['id' => '124', 'name' => 'libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'calling_code' => '+218'],
            ['id' => '125', 'name' => 'liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'calling_code' => '+423'],
            ['id' => '126', 'name' => 'lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'calling_code' => '+370'],
            ['id' => '127', 'name' => 'luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'calling_code' => '+352'],
            ['id' => '128', 'name' => 'macau s.a.r.', 'iso2' => 'MO', 'iso3' => 'MAC', 'calling_code' => '+853'],
            ['id' => '129', 'name' => 'macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'calling_code' => '+389'],
            ['id' => '130', 'name' => 'madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'calling_code' => '+261'],
            ['id' => '131', 'name' => 'malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'calling_code' => '+265'],
            ['id' => '132', 'name' => 'malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'calling_code' => '+60'],
            ['id' => '133', 'name' => 'maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'calling_code' => '+960'],
            ['id' => '134', 'name' => 'mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'calling_code' => '+223'],
            ['id' => '135', 'name' => 'malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'calling_code' => '+356'],
            ['id' => '136', 'name' => 'man (isle of)', 'iso2' => 'IM', 'iso3' => 'IMN', 'calling_code' => '+44'],
            ['id' => '137', 'name' => 'marshall islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'calling_code' => '+692'],
            ['id' => '138', 'name' => 'martinique', 'iso2' => 'MQ', 'iso3' => 'MTQ', 'calling_code' => '+596'],
            ['id' => '139', 'name' => 'mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'calling_code' => '+222'],
            ['id' => '140', 'name' => 'mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'calling_code' => '+230'],
            ['id' => '141', 'name' => 'mayotte', 'iso2' => 'YT', 'iso3' => 'MYT', 'calling_code' => '+262'],
            ['id' => '142', 'name' => 'mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'calling_code' => '+52'],
            ['id' => '143', 'name' => 'micronesia', 'iso2' => 'FM', 'iso3' => 'FSM', 'calling_code' => '+691'],
            ['id' => '144', 'name' => 'moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'calling_code' => '+373'],
            ['id' => '145', 'name' => 'monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'calling_code' => '+377'],
            ['id' => '146', 'name' => 'mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'calling_code' => '+976'],
            ['id' => '147', 'name' => 'montserrat', 'iso2' => 'MS', 'iso3' => 'MSR', 'calling_code' => '+1664'],
            ['id' => '148', 'name' => 'morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'calling_code' => '+212'],
            ['id' => '149', 'name' => 'mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'calling_code' => '+258'],
            ['id' => '150', 'name' => 'myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'calling_code' => '+95'],
            ['id' => '151', 'name' => 'namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'calling_code' => '+264'],
            ['id' => '152', 'name' => 'nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'calling_code' => '+674'],
            ['id' => '153', 'name' => 'nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'calling_code' => '+977'],
            ['id' => '154', 'name' => 'netherlands antilles', 'iso2' => 'AN', 'iso3' => 'ANT', 'calling_code' => '+599'],
            ['id' => '155', 'name' => 'netherlands the', 'iso2' => 'NL', 'iso3' => 'NLD', 'calling_code' => '+31'],
            ['id' => '156', 'name' => 'new caledonia', 'iso2' => 'NC', 'iso3' => 'NCL', 'calling_code' => '+687'],
            ['id' => '157', 'name' => 'new zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'calling_code' => '+64'],
            ['id' => '158', 'name' => 'nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'calling_code' => '+505'],
            ['id' => '159', 'name' => 'niger', 'iso2' => 'NE', 'iso3' => 'NER', 'calling_code' => '+227'],
            ['id' => '160', 'name' => 'nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'calling_code' => '+234'],
            ['id' => '161', 'name' => 'niue', 'iso2' => 'NU', 'iso3' => 'NIU', 'calling_code' => '+683'],
            ['id' => '162', 'name' => 'norfolk island', 'iso2' => 'NF', 'iso3' => 'NFK', 'calling_code' => '+672'],
            ['id' => '163', 'name' => 'northern mariana islands', 'iso2' => 'MP', 'iso3' => 'MNP', 'calling_code' => '+1670'],
            ['id' => '164', 'name' => 'norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'calling_code' => '+47'],
            ['id' => '165', 'name' => 'oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'calling_code' => '+968'],
            ['id' => '166', 'name' => 'pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'calling_code' => '+92'],
            ['id' => '167', 'name' => 'palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'calling_code' => '+680'],
            ['id' => '168', 'name' => 'palestinian territory occupied', 'iso2' => 'PS', 'iso3' => 'PSE', 'calling_code' => '+970'],
            ['id' => '169', 'name' => 'panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'calling_code' => '+507'],
            ['id' => '170', 'name' => 'papua new guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'calling_code' => '+675'],
            ['id' => '171', 'name' => 'paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'calling_code' => '+595'],
            ['id' => '172', 'name' => 'peru', 'iso2' => 'PE', 'iso3' => 'PER', 'calling_code' => '+51'],
            ['id' => '173', 'name' => 'philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'calling_code' => '+63'],
            ['id' => '174', 'name' => 'pitcairn island', 'iso2' => 'PN', 'iso3' => 'PCN', 'calling_code' => '+64'],
            ['id' => '175', 'name' => 'poland', 'iso2' => 'PL', 'iso3' => 'POL', 'calling_code' => '+48'],
            ['id' => '176', 'name' => 'portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'calling_code' => '+351'],
            ['id' => '177', 'name' => 'puerto rico', 'iso2' => 'PR', 'iso3' => 'PRI', 'calling_code' => '+1'],
            ['id' => '178', 'name' => 'qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'calling_code' => '+974'],
            ['id' => '179', 'name' => 'reunion', 'iso2' => 'RE', 'iso3' => 'REU', 'calling_code' => '+262'],
            ['id' => '180', 'name' => 'romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'calling_code' => '+40'],
            ['id' => '181', 'name' => 'russia', 'iso2' => 'RU', 'iso3' => 'RUS', 'calling_code' => '+7'],
            ['id' => '182', 'name' => 'rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'calling_code' => '+250'],
            ['id' => '183', 'name' => 'saint helena', 'iso2' => 'SH', 'iso3' => 'SHN', 'calling_code' => '+290'],
            ['id' => '184', 'name' => 'saint kitts and nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'calling_code' => '+1869'],
            ['id' => '185', 'name' => 'saint lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'calling_code' => '+1758'],
            ['id' => '186', 'name' => 'saint pierre and miquelon', 'iso2' => 'PM', 'iso3' => 'SPM', 'calling_code' => '+508'],
            ['id' => '187', 'name' => 'saint vincent and the grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'calling_code' => '+1784'],
            ['id' => '188', 'name' => 'samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'calling_code' => '+685'],
            ['id' => '189', 'name' => 'san marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'calling_code' => '+378'],
            ['id' => '190', 'name' => 'sao tome and principe', 'iso2' => 'ST', 'iso3' => 'STP', 'calling_code' => '+239'],
            ['id' => '191', 'name' => 'saudi arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'calling_code' => '+966'],
            ['id' => '192', 'name' => 'senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'calling_code' => '+221'],
            ['id' => '193', 'name' => 'serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'calling_code' => '+381'],
            ['id' => '194', 'name' => 'seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'calling_code' => '+248'],
            ['id' => '195', 'name' => 'sierra leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'calling_code' => '+232'],
            ['id' => '196', 'name' => 'singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'calling_code' => '+65'],
            ['id' => '197', 'name' => 'slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'calling_code' => '+421'],
            ['id' => '198', 'name' => 'slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'calling_code' => '+386'],
            ['id' => '199', 'name' => 'smaller territories of the uk', 'iso2' => 'GB', 'iso3' => 'GBR', 'calling_code' => '+44'],
            ['id' => '200', 'name' => 'solomon islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'calling_code' => '+677'],
            ['id' => '201', 'name' => 'somalia', 'iso2' => 'SO', 'iso3' => 'SOM', 'calling_code' => '+252'],
            ['id' => '202', 'name' => 'south africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'calling_code' => '+27'],
            ['id' => '203', 'name' => 'south georgia', 'iso2' => 'GS', 'iso3' => 'SGS', 'calling_code' => '+500'],
            ['id' => '204', 'name' => 'south sudan', 'iso2' => 'SS', 'iso3' => 'SSD', 'calling_code' => '+211'],
            ['id' => '205', 'name' => 'spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'calling_code' => '+34'],
            ['id' => '206', 'name' => 'sri lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'calling_code' => '+94'],
            ['id' => '207', 'name' => 'sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'calling_code' => '+249'],
            ['id' => '208', 'name' => 'suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'calling_code' => '+597'],
            ['id' => '209', 'name' => 'svalbard and jan mayen islands', 'iso2' => 'SJ', 'iso3' => 'SJM', 'calling_code' => '+47'],
            ['id' => '210', 'name' => 'swaziland', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'calling_code' => '+268'],
            ['id' => '211', 'name' => 'sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'calling_code' => '+46'],
            ['id' => '212', 'name' => 'switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'calling_code' => '+41'],
            ['id' => '213', 'name' => 'syria', 'iso2' => 'SY', 'iso3' => 'SYR', 'calling_code' => '+963'],
            ['id' => '214', 'name' => 'taiwan', 'iso2' => 'TW', 'iso3' => 'TWN', 'calling_code' => '+886'],
            ['id' => '215', 'name' => 'tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'calling_code' => '+992'],
            ['id' => '216', 'name' => 'tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'calling_code' => '+255'],
            ['id' => '217', 'name' => 'thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'calling_code' => '+66'],
            ['id' => '218', 'name' => 'togo', 'iso2' => 'TG', 'iso3' => 'TGO', 'calling_code' => '+228'],
            ['id' => '219', 'name' => 'tokelau', 'iso2' => 'TK', 'iso3' => 'TKL', 'calling_code' => '+690'],
            ['id' => '220', 'name' => 'tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'calling_code' => '+676'],
            ['id' => '221', 'name' => 'trinidad and tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'calling_code' => '+1'],
            ['id' => '222', 'name' => 'tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'calling_code' => '+216'],
            ['id' => '223', 'name' => 'turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'calling_code' => '+90'],
            ['id' => '224', 'name' => 'turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'calling_code' => '+993'],
            ['id' => '225', 'name' => 'turks and caicos islands', 'iso2' => 'TC', 'iso3' => 'TCA', 'calling_code' => '+1'],
            ['id' => '226', 'name' => 'tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'calling_code' => '+688'],
            ['id' => '227', 'name' => 'uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'calling_code' => '+256'],
            ['id' => '228', 'name' => 'ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'calling_code' => '+380'],
            ['id' => '229', 'name' => 'united arab emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'calling_code' => '+971'],
            ['id' => '230', 'name' => 'united kingdom', 'iso2' => 'GB', 'iso3' => 'GBR', 'calling_code' => '+44'],
            ['id' => '231', 'name' => 'united states', 'iso2' => 'US', 'iso3' => 'USA', 'calling_code' => '+1'],
            ['id' => '232', 'name' => 'united states minor outlying islands', 'iso2' => 'UM', 'iso3' => 'UMI', 'calling_code' => '+1'],
            ['id' => '233', 'name' => 'uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'calling_code' => '+598'],
            ['id' => '234', 'name' => 'uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'calling_code' => '+998'],
            ['id' => '235', 'name' => 'vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'calling_code' => '+678'],
            ['id' => '236', 'name' => 'vatican city state (holy see)', 'iso2' => 'VA', 'iso3' => 'VAT', 'calling_code' => '+379'],
            ['id' => '237', 'name' => 'venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'calling_code' => '+58'],
            ['id' => '238', 'name' => 'vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'calling_code' => '+84'],
            ['id' => '239', 'name' => 'virgin islands (british)', 'iso2' => 'VG', 'iso3' => 'VGB', 'calling_code' => '+1'],
            ['id' => '240', 'name' => 'virgin islands (us)', 'iso2' => 'VI', 'iso3' => 'VIR', 'calling_code' => '+1'],
            ['id' => '241', 'name' => 'wallis and futuna islands', 'iso2' => 'WF', 'iso3' => 'WLF', 'calling_code' => '+681'],
            ['id' => '242', 'name' => 'western sahara', 'iso2' => 'EH', 'iso3' => 'ESH', 'calling_code' => '+212'],
            ['id' => '243', 'name' => 'yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'calling_code' => '+967'],
            ['id' => '244', 'name' => 'yugoslavia', 'iso2' => 'YU', 'iso3' => 'YUG', 'calling_code' => ''],
            ['id' => '245', 'name' => 'zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'calling_code' => '+260'],
            ['id' => '246', 'name' => 'zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'calling_code' => '+263']
        ];
    }
}
